return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	main = "nvim-treesitter",
	opts = {
		ensure_installed = {
			"apex",
			"dockerfile",
			"javascript",
			"json",
			"lua",
			"go",
			"gomod",
			"gosum",
			"proto",
			"regex",
			"terraform",
			"typescript",
			"markdown",
			"markdown_inline",
			"sql",
			"yaml",
		},
		auto_install = true,
	},
}
